<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html  xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh" lang="zh">
<!-- generated by to_html.pl from try.xml -->
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>异常处理</title>
	<meta name="author" content="W.Dee" />
	<meta http-equiv="Content-Style-Type" content="text/css" />
	<meta http-equiv="Content-Script-Type" content="text/javascript" />
	<link href="browser.css" type="text/css" rel="stylesheet" title="åéåéç¸å³æ ååèæ ·å¼" />
	<link href="mailto:dee@kikyou.info" rev="Made" />
	<link href="index.html" target="_top" rel="Start" title="é¦é¡µ" />
</head>
<body>
<h1><a id="id368" name="id368">异常处理</a>
</h1><div class="para"><div>
　<a id="id369" name="id369" class="targanchor"><dfn>异常</dfn></a>是指正常情况下不会发生的所谓「例外」的情况。在大部分情况下异常和错误可以当作同义词。<br />
</div></div>
<h1><a id="id370" name="id370">异常会发生的地方</a>
</h1><div class="para"><div>
　程序的任何地方都有发生异常的可能性。<br />
　发生异常的时候，异常将被「投出(throw)」。<br />
　比如说，以下的脚本将会引起错误。<br />
<br />

<br />
<code class="bq"><span class="weak">例:</span><br />&nbsp;&nbsp;&nbsp;&nbsp;&quot;3%0&quot;!;&nbsp;<span class="comment">//&nbsp;发生“除以0错误”的异常</span></code>
<br />

<br />
　虽然有像上例一样明显会发生异常的情况，但也有一些情况下，无法知道代码是否一定会发生异常。<br />
</div></div>
<h1><a id="id371" name="id371">异常的捕捉</a>
</h1><div class="para"><div>
　使用 <code class="inlinecode"><a id="id372" name="id372" class="targanchor"><dfn>try</dfn></a></code> (尝试) 关键字和 <code class="inlinecode"><a id="id373" name="id373" class="targanchor"><dfn>catch</dfn></a></code> (捕捉) 关键字，可以捕捉异常。<br />
　例如说，为了捕捉上面所说的“不知道是否会发生的异常”，可以象下面这样编写代码。<br />
<br />

<br />
<code class="bq"><span class="weak">例:</span><br />&nbsp;&nbsp;&nbsp;&nbsp;try&nbsp;<span class="comment">//&nbsp;不知道是否会发生异常</span><br />
&nbsp;&nbsp;&nbsp;&nbsp;{<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;func1();&nbsp;<span class="comment">//&nbsp;这里有可能会发生异常</span><br />
&nbsp;&nbsp;&nbsp;&nbsp;}<br />
&nbsp;&nbsp;&nbsp;&nbsp;catch&nbsp;<span class="comment">//&nbsp;捕捉异常</span><br />
&nbsp;&nbsp;&nbsp;&nbsp;{<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="comment">//&nbsp;当发生异常的时候，这里的代码被执行</span><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;inform(&quot;无法读取图像。&quot;);&nbsp;<span class="comment">//&nbsp;显示信息</span><br />
&nbsp;&nbsp;&nbsp;&nbsp;}<br />
</code>
<br />

<br />
　像这样在 try 代码段中编写可能会发生异常的代码，就可以在发生异常的时候执行 catch 代码段中的代码。利用这个功能，可以编写出清晰流畅的错误处理代码。<br />
<br />
　在 try 代码段中没有发生任何异常的情况下，catch 代码段不会被执行。<br />
<br />
　try 代码段中可以编写任何的代码。除了在代码段中直接发生异常的情况之外，在代码段中调用的函数，以及被函数调用的函数中发生的异常，try ... catch 代码都可以捕捉到。<br />
<br />
　发生异常的情况下，代码段剩下的执行步骤将被中断，并返回到 try 语句的位置。<br />
<br />
　如果在 catch 代码段中也发生了异常，该异常便无法在这个 catch 代码段中被捕捉。这个异常将会按照调用上下文向上回溯，如果在发生错误的 catch 代码上层存在 try 语句，则异常将在那里被捕捉。<br />
<br />
　在异常被抛出之后，程序到达 catch 块之前有发生其他异常的可能性，但这种情况下的操作未被定义。<br />
<br />
　如果异常在脚本中完全没有被捕捉到，则异常将离开脚本而被传递给应用程序，由应用程序来进行处理。<br />
<br /><div class="note"><div class="notehead"><span class="noteheadspan">Note</span></div>
一般来说，由于错误而被抛出的异常会中断脚本的执行，所以建议尽可能在可能发生错误的地方写入 try ... catch 。</div><br />
</div></div>
<h1><a id="id374" name="id374">异常对象</a>
</h1><div class="para"><div>
　关于异常的各种各样的欣喜，都会和一个 <a id="id375" name="id375" class="targanchor"><dfn>Exception</dfn></a> 类的对象一起被投出。这个对象被称做异常对象，可以通过 catch 语句来获取。<br />
　例如说，我们可以编写以下代码。<br />

<br />
<code class="bq"><span class="weak">例:</span><br />&nbsp;&nbsp;&nbsp;&nbsp;try<br />
&nbsp;&nbsp;&nbsp;&nbsp;{<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;loadImages(&quot;nothing.jpeg&quot;);&nbsp;<span class="comment">//&nbsp;可能会发生异常的操作</span><br />
&nbsp;&nbsp;&nbsp;&nbsp;}<br />
&nbsp;&nbsp;&nbsp;&nbsp;catch&nbsp;(e)&nbsp;<span class="comment">//&nbsp;利用&nbsp;e&nbsp;这个变量获取异常对象</span><br />
&nbsp;&nbsp;&nbsp;&nbsp;{<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="comment">//&nbsp;e.message&nbsp;是和异常一起投出的消息字符串。</span><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="comment">//&nbsp;一些情况下发生异常的理由会通过这个变量说明。</span><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;inform(&quot;无法读取图像。\n&quot;+e.message);<br />
&nbsp;&nbsp;&nbsp;&nbsp;}<br />
</code>
<br />

　像这样，在 catch 后的括号中写入变量名，就可以利用这个变量接收异常对象。<br />
　这个变量的作用域，从 catch 后的代码段中开始，并随着程序离开这个代码段而结束。此外，这个变量不需要事先的声明。<br />
</div></div>
<h1><a id="id376" name="id376">throw 语句</a>
</h1><div class="para"><div>
　在 TJS 程序中可以使用 <code class="inlinecode"><a id="id377" name="id377" class="targanchor"><dfn>throw</dfn></a></code> 关键字投出异常。<br />
　例如，我们可以编写如下代码。<br />

<br />
<code class="bq"><span class="weak">例:</span><br />&nbsp;&nbsp;&nbsp;&nbsp;function&nbsp;pow2(n)<br />
&nbsp;&nbsp;&nbsp;&nbsp;{<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="comment">//&nbsp;计算&nbsp;2&nbsp;的&nbsp;n&nbsp;次幂，提供的&nbsp;n&nbsp;必须是正整数</span><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if(n&lt;0)&nbsp;throw&nbsp;new&nbsp;Exception(&quot;不能指定负数。&quot;);<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="comment">//&nbsp;↑&nbsp;发生异常</span><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;1&lt;&lt;n;<br />
&nbsp;&nbsp;&nbsp;&nbsp;}<br />
</code>
<br />

　如果给这个函数传递了类似于 -1 这样的负数，就会发生异常。投出异常可以使用类似以下的语句。<br />
<br />

<br />
<code class="bq">throw&nbsp;new&nbsp;Exception(&quot;不能指定负数。&quot;);</code>
<br />

<br />
　<code class="inlinecode">new Exception(&quot;不能指定负数。&quot;)</code> 这个语句将以字符串作为参数创建一个新的 Exception 类对象（详细请参考 Exception 类的说明）。然后将这个新创建的对象通过 throw 关键字投出。<br />
　throw 关键字能投出的对象并非一定要是 Exception 类的对象，数字也好，字符串也好，包括对函数的引用也能够被投出。但是，我们推荐投出 Exception 类，或者这个类的派生类的对象。这样，在 catch 代码段中只需要统一编写对应 Exception 类对象的代码即可。<br />
</div></div>
<h1><a id="id378" name="id378">再次投出异常</a>
</h1><div class="para"><div>
　catch 可以捕捉到发生的异常，但在直接对应的 try 块的上层也有可能声明了别的 try 语句。在这种情况下，可以再次投出异常。<br />
　我们可以编写如下代码。<br />

<br />
<code class="bq"><span class="weak">例:</span><br />&nbsp;&nbsp;&nbsp;&nbsp;function&nbsp;tryloadimage()<br />
&nbsp;&nbsp;&nbsp;&nbsp;{<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;try<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;primaryLayer.loadImages(&quot;test1.bmp&quot;);&nbsp;<span class="comment">//&nbsp;尝试读取test1.bmp</span><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;catch(e)<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;inform(&quot;图像读取失败。&quot;);<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;e;&nbsp;<span class="comment">//&nbsp;上面的信息被显示的同时，异常会被再次投出</span><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br />
&nbsp;&nbsp;&nbsp;&nbsp;}<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;function&nbsp;test()<br />
&nbsp;&nbsp;&nbsp;&nbsp;{<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="comment">//&nbsp;调用&nbsp;tryloadimage&nbsp;，如果读取图像成功则返回&nbsp;true</span><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="comment">//&nbsp;否则返回&nbsp;false&nbsp;的函数</span><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;try<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tryloadimage();<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;catch<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;false;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;true;<br />
&nbsp;&nbsp;&nbsp;&nbsp;}<br />
</code>
<br />

　在这种情况下调用 test() ，并且图像读取失败，那么在 inform 方法显示出消息的同时，由于异常被再次投出，可以通过 test 函数内的 catch 代码进行捕捉。<br />
</div></div>
	<script type="text/javascript" charset="UTF-8" src="documentid.js" ></script>
	<script type="text/javascript" charset="UTF-8" src="postcontent.js" ></script>
</body>
</html>
